import «Lp2lc».Active.STLC.Proof

namespace Lp2lc.Active.STLC

namespace Example

-- contains verified examples and test cases of things in Def

-- All docstrings use short (under 5 lines) of Scala code as demonstrations.
variablefreeTmable
end Example
Tm
enfunction
notArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrownotArrow
variableTm
freeVariable
function
